const products = [
    {
        _id: '1',
        name: 'Airpod',
        image: '../public/images/airpods.jpg',
        description: 'Wireless Airpods with Lightning Charging Case Included. Over 24 Hours of Battery Life, Effortless Setup. Bluetooth Headphones for iPhone',
        brand: 'Apple',
        category: 'Electronics',
        price: '90.00',
        CountInStock: '10',
        rating: '4.5',
        numReviews: '8',
    },
    {
        _id: '2',
        name: 'Alexa',
        image: '../public/images/alexa.jpg',
        description: 'Alexa is an intelligent personal assistant that makes use of machine learning and artificial intelligence. It is designed to be always on and woken with a voice command',
        brand: 'Amazon',
        category: 'Electronics',
        price: '75.00',
        CountInStock: '8',
        rating: '4.2',
        numReviews: '13',
    },
    {
        _id: '3',
        name: 'Camera',
        image: '../public/images/camera.jpg',
        description: '4K Digital Camera for Photography Autofocus, 48MP Vlogging Camera with SD Card Anti-Shake',
        brand: 'Samsung',
        category: 'Electronics',
        price: '100.00',
        CountInStock: '12',
        rating: '5.0',
        numReviews: '20',
    },
    {
        _id: '1',
        name: 'Airpod',
        image: '../public/images/airpods.jpg',
        description: 'Wireless Airpods with Lightning Charging Case Included. Over 24 Hours of Battery Life, Effortless Setup. Bluetooth Headphones for iPhone',
        brand: 'Apple',
        category: 'Electronics',
        price: '90.00',
        CountInStock: '10',
        rating: '4.5',
        numReviews: '8',
    },
    {
        _id: '2',
        name: 'Alexa',
        image: '../public/images/alexa.jpg',
        description: 'Alexa is an intelligent personal assistant that makes use of machine learning and artificial intelligence. It is designed to be always on and woken with a voice command',
        brand: 'Amazon',
        category: 'Electronics',
        price: '75.00',
        CountInStock: '8',
        rating: '4.2',
        numReviews: '13',
    },
    {
        _id: '3',
        name: 'Camera',
        image: '../public/images/camera.jpg',
        description: '4K Digital Camera for Photography Autofocus, 48MP Vlogging Camera with SD Card Anti-Shake',
        brand: 'Samsung',
        category: 'Electronics',
        price: '100.00',
        CountInStock: '12',
        rating: '5.0',
        numReviews: '20',
    },
]

export default products;
